#!/bin/bash

. /opt/fuzetsu/fuzetsu-envs
MYVMPATH=`eval echo ~$(whoami)`/fuzetsutmp

if [ "$1" = "build" ]
then
	if [ $# -lt 4 ]
	then
		echo fuzetsu build \<app_template_name\> \<src\> \<target_name\>
		exit 1
	fi

	TEMPLATE_NAME="$2"
	SRC_FILE="$3"
	VMNAME="$4"

	TMP_DIR="/dev/shm/fuzetsu-$(date +%s%N)-$$-$RANDOM"

	mkdir -p "$TMP_DIR/appitself"

	# file size in blocks. not suitable for hard coding.
	# block size is 512 bytes. 1638400 is as large as 800MiB.
	ulimit -f 1638400
	
	lxc-destroy -f -p $MYVMPATH -n $VMNAME -n $TEMPLATE_NAME >/dev/null
	lxc-copy -p $VMPATH -P $MYVMPATH -N $VMNAME -n $TEMPLATE_NAME -B overlayfs -s >/dev/null
	lxc-start -P $MYVMPATH -n $VMNAME -d --logfile /tmp/fuzetsu.log
	lxc-wait -P $MYVMPATH -n $VMNAME -s RUNNING
	lxc-attach -P $MYVMPATH -n $VMNAME -- /bin/bash -c 'echo 127.0.1.1 $(hostname) >> /etc/hosts'
	lxc-attach < $SRC_FILE > /dev/null -P $MYVMPATH -n $VMNAME -- /usr/bin/tee $HOME_IN_CONTAINER/target.file
	# TODO: catch error from lxc
	lxc-attach > "$TMP_DIR/appitself/error.log" 2>&1 -P $MYVMPATH -n $VMNAME -- timeout -sKILL $COMPILING_SECONDS_LIMIT /bin/bash -c 'ulimit -Hf 1638400; sudo -u ubuntu /usr/bin/compile '$HOME_IN_CONTAINER/target.file
	er=$?
	lxc-stop -P $MYVMPATH -n $VMNAME

	cat "$TMP_DIR/appitself/error.log"

	if [ $er -ne 0 ]
	then
		rm -Rf "$TMP_DIR"
		exit $er
	fi

	exit 0
fi


if [ "$1" = "run" ]
then
	cat > /tmp/fuzetsuinput
	if [ $# -lt 2 ]
	then
		echo fuzetsu run \</target_name\>
		exit 1
	fi
	# file size in blocks. not suitable for hard coding.
	# block size is 512 bytes. 1638400 is as large as 800MiB.
	ulimit -f 1638400

	TMP_VMNAME="$(date +%s%N)-$$-$RANDOM"
	VMNAME="$2"

	lxc-copy -P $MYVMPATH -p $MYVMPATH -N $TMP_VMNAME -n $VMNAME -B overlayfs -s >/dev/null
	lxc-start -P $MYVMPATH -n $TMP_VMNAME -d >/dev/null
	lxc-wait -P $MYVMPATH -n $TMP_VMNAME -s RUNNING >/dev/null
	start_time=`date +%s%N`
	lxc-attach -P $MYVMPATH -n $TMP_VMNAME -- /bin/bash -c 'ulimit -Hf 1638400; timeout -sKILL '$RUNNING_SECONDS_LIMIT' sudo -u ubuntu /usr/bin/time -o /home/ubuntu/fuzetsu-mem-usage -f "%M" --quiet `cat /usr/bin/run`' < /tmp/fuzetsuinput
	er=$?
	end_time=`date +%s%N`
	lxc-attach -P $MYVMPATH -n $TMP_VMNAME cat /home/ubuntu/fuzetsu-mem-usage | tail -n 1 > /tmp/fuzetsu-mem-usage
	echo `expr $end_time - $start_time` > /tmp/fuzetsu-time-ns
	tail -n 1 /tmp/fuzetsu-time-tmp > /tmp/fuzetsu-time
	rm /tmp/fuzetsu-time-tmp
	lxc-stop -k -P $MYVMPATH -n $TMP_VMNAME -t 3 >/dev/null
	lxc-destroy -P $MYVMPATH -n $TMP_VMNAME -f >/dev/null

	rm /tmp/fuzetsuinput

	exit $er
fi

if [ "$1" = "ls" ]
then
	lxc-ls -P $MYVMPATH
	exit $?
fi

if [ "$1" = "destroy" ]
then
	if [ $# -lt 2 ]
	then
		echo fuzetsu destroy \</target_name\>
		exit 1
	fi

	VMNAME="$2"

	lxc-destroy -P $MYVMPATH -n $VMNAME
	exit $?
fi

echo 'Command Not Found'
exit 1
