#!/bin/bash

. /usr/bin/fuzetsu-envs
MYVMPATH=`eval echo ~$(whoami)`/fuzetsutmp

if [ "$1" = "build" ]
then
	if [ $# -lt 4 ]
	then
		echo fuzetsu lxc build \<app_template_name\> \<src\> \<target_name\>
		exit 1
	fi

	TEMPLATE_NAME="$2"
	SRC_FILE="$3"
	VMNAME="$4"

	TMP_DIR="/dev/shm/fuzetsu-$(date +%s%N)-$$-$RANDOM"

	mkdir -p "$TMP_DIR/appitself"

	# file size in blocks. not suitable for hard coding.
	# block size is 512 bytes. 1638400 is as large as 800MiB.
	ulimit -f 1638400
	
	lxc-destroy -f -P $MYVMPATH -n $VMNAME >/dev/null
	lxc-copy -p $VMPATH -P $MYVMPATH -N $VMNAME -n $TEMPLATE_NAME -B overlayfs -s >/dev/null
	lxc-start -P $MYVMPATH -n $VMNAME -d --logfile /tmp/fuzetsu.log
	lxc-wait -P $MYVMPATH -n $VMNAME -s RUNNING
	lxc-attach > /dev/null -P $MYVMPATH -n $VMNAME -- /bin/bash -c 'echo 127.0.1.1 $(hostname) >> /etc/hosts'
	lxc-attach < $SRC_FILE > /dev/null -P $MYVMPATH -n $VMNAME -- /usr/bin/tee $HOME_IN_CONTAINER/target.file
	# TODO: catch error from lxc
	lxc-attach > "$TMP_DIR/appitself/error.log" 2>&1 -P $MYVMPATH -n $VMNAME -- timeout -sKILL $COMPILING_SECONDS_LIMIT /bin/bash -c 'ulimit -Hf 1638400; sudo -u ubuntu /usr/bin/compile '$HOME_IN_CONTAINER/target.file
	er=$?
	lxc-stop -P $MYVMPATH -n $VMNAME -t 3

	# output up to 1048576 bytes.
	head -c 1048576 -n 1048576 "$TMP_DIR/appitself/error.log"

	if [ $er -ne 0 ]
	then
		rm -Rf "$TMP_DIR"
		exit $er
	fi

	exit 0
fi


if [ "$1" = "run" ]
then
	if [ $# -lt 3 ]
	then
		echo fuzetsu lxc run \</target_name\> \<time_out\>
		exit 1
	fi

	cat > /tmp/fuzetsuinput

	# file size in blocks. not suitable for hard coding.
	# block size is 512 bytes. 1638400 is as large as 800MiB.
	ulimit -f 1638400

	TMP_VMNAME="$(date +%s%N)-$$-$RANDOM"
	VMNAME="$2"
	TIMEOUT_IN_SEC="$3"

	lxc-copy -P $MYVMPATH -p $MYVMPATH -N $TMP_VMNAME -n $VMNAME -B overlayfs -s >/dev/null
	lxc-start -P $MYVMPATH -n $TMP_VMNAME -d >/dev/null
	lxc-wait -P $MYVMPATH -n $TMP_VMNAME -s RUNNING >/dev/null
	lxc-attach >/dev/null  2&>1 -P $MYVMPATH -n $TMP_VMNAME -- /bin/bash -c 'echo 127.0.1.1 $(hostname) >> /etc/hosts'
	start_time=`date +%s%N`
	lxc-attach 2> /dev/null -P $MYVMPATH -n $TMP_VMNAME -- /bin/bash -c 'ulimit -Hf 1638400; timeout -sKILL '$TIMEOUT_IN_SEC' sudo -u ubuntu /usr/bin/time -o /home/ubuntu/fuzetsu-mem-usage -f "%M" --quiet `cat /usr/bin/run`' < /tmp/fuzetsuinput >/tmp/fuzetsuoutput
	er=$?
	end_time=`date +%s%N`
	# output up to 1048576 bytes.
	head -c 1048576 -n 1048576 /tmp/fuzetsuoutput
	rm /tmp/fuzetsuoutput

	lxc-attach 2> /dev/null -P $MYVMPATH -n $TMP_VMNAME cat /home/ubuntu/fuzetsu-mem-usage | tail -n 1 > /tmp/fuzetsu-mem-usage
	echo `expr $end_time - $start_time` > /tmp/fuzetsu-time-ns
	lxc-stop -k -P $MYVMPATH -n $TMP_VMNAME >/dev/null
	lxc-destroy -P $MYVMPATH -n $TMP_VMNAME -f >/dev/null

	rm /tmp/fuzetsuinput

	exit $er
fi

if [ "$1" = "ls" ]
then
	lxc-ls -P $MYVMPATH
	exit $?
fi

if [ "$1" = "destroy" ]
then
	if [ $# -lt 2 ]
	then
		echo fuzetsu destroy \</target_name\>
		exit 1
	fi

	VMNAME="$2"

	lxc-destroy -P $MYVMPATH -n $VMNAME -f
	exit $?
fi

echo 'Command Not Found'
exit 1
