#!/bin/bash

if [ "$1" = "lxc" ]
then
	shift
	/opt/fuzetsu/fuzetsu-lxc $@
	exit $?
fi

if [ "$1" = "osv" ]
then
	shift
	/opt/fuzetsu/fuzetsu-osv $@
	exit $?
fi

echo "Command not found by fuzetsu"
exit 1
